import type {
  CounterContextValue,
  CounterSessionValue,
} from "@/features/counter/context/counterTypes";

export function createCounterSessionValue(
  value: CounterContextValue,
): CounterSessionValue {
  return {
    ready: value.ready,
    preset: value.preset,
    setupSource: value.setupSource,
    wbcCount: value.wbcCount,
    increase: value.increase,
    view: value.view,
    keyboardType: value.keyboardType,
    isHandset: value.isHandset,
    stats: value.stats,
    tallyValue: value.tallyValue,
    corrected: value.corrected,
    ancValue: value.ancValue,
    alcValue: value.alcValue,
    me: value.me,
    flashRowId: value.flashRowId,
    flashKey: value.flashKey,
    flashTick: value.flashTick,
    shake: value.shake,
    keyErrorId: value.keyErrorId,
    capture: value.capture,
    captureLabel: value.captureLabel,
    captureNotice: value.captureNotice,
    morphology: value.morphology,
    estimate: value.estimate,
    setWbcCount: value.setWbcCount,
    setIncrease: value.setIncrease,
    setView: value.setView,
    setKeyboardType: value.setKeyboardType,
    setMaxWBC: value.setMaxWBC,
    updateRow: value.updateRow,
    addRow: value.addRow,
    removeRow: value.removeRow,
    reorderRows: value.reorderRows,
    bindRowKey: value.bindRowKey,
    startCapture: value.startCapture,
    cancelCapture: value.cancelCapture,
    captureKey: value.captureKey,
    clearSession: value.clearSession,
    undo: value.undo,
    bumpRow: value.bumpRow,
    setMorphology: value.setMorphology,
    setEstimateMeta: value.setEstimateMeta,
    updateEstimateCell: value.updateEstimateCell,
    addEstimateCell: value.addEstimateCell,
    removeEstimateCell: value.removeEstimateCell,
    bindEstimateKey: value.bindEstimateKey,
    bumpEstimateCell: value.bumpEstimateCell,
    bumpField: value.bumpField,
    setRuntimeActive: value.setRuntimeActive,
  };
}
